import turtle 
screen = turtle.Screen()
h = turtle.Turtle()
h.color("green")
h.begin_fill()
h.pensize(3)
h.left(50)
h.forward(133)
h.circle(50,200)
h.right(140)
h.circle(50,200)
h.forward(133)
h.end_fill()
h.penup()
h.goto(-65,130)
h.pendown()
h.color('white')
h.write("example",font=("Verdana",20,"bold"))
turtle.done()

